# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer

contracts:
  - name: RelayDepository
    handler: src/EventHandlers.ts
    events:
    - event: RelayErc20Deposit(address from, address token, uint256 amount, bytes32 id)
    - event: RelayNativeDeposit(address from, uint256 amount, bytes32 id)
networks:
- id: 1 # Ethereum
  start_block: 0
  contracts:
  - name: RelayDepository
    address: 0x4cD00E387622C35bDDB9b4c962C136462338BC31

- id: 10 # Optimism
  start_block: 0
  contracts:
  - name: RelayDepository
    address: 0x4cD00E387622C35bDDB9b4c962C136462338BC31
- id: 8453 # Base
  start_block: 0
  contracts:
  - name: RelayDepository
    address: 0x4cD00E387622C35bDDB9b4c962C136462338BC31
