# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: ERC1967Proxy
    address:
    - 0x6818809EefCe719E480a7526D76bD3e561526b46
    handler: src/EventHandlers.ts
    events:
    - event: Deposited(address indexed _depositor, address indexed _pool, uint256 _commitment, uint256 _amount)
    - event: FeesWithdrawn(address _asset, address _recipient, uint256 _amount)
    - event: RootUpdated(uint256 _root, string _ipfsCID, uint256 _timestamp)
    - event: WithdrawalRelayed(address indexed _relayer, address indexed _recipient, address indexed _asset, uint256 _amount, uint256 _feeAmount)
unordered_multichain_mode: true
preload_handlers: true
